# Generated by Django 3.2 on 2021-04-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=264)),
                ('blog_descritions', models.CharField(max_length=264)),
                ('blog_date', models.DateField()),
                ('blog_url', models.URLField(blank=True)),
            ],
        ),
    ]
